### ISSUE TITLE
MOSES Install.html.

### ISSUE THREAD

**Issue by ForeverTangent** [M-O-S-E-S/mgm#11]
I am trying to get mgm-defunct going on a virtual machine.

I have followed the install instructions completely, but when I get to creating the admin by visiting the install.html page, all I see is a blank webpage.  I know my Browsers are loading the code, because I can check the page source, but nothing is displayed.

The only lead I can find is that when I look at the JavaScript console I see the following message that looks like an error.
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]
GET XHR http://localhost/server/install/test [HTTP/1.0 500 Internal Server Error 4ms]

Thanks in advance for any help.

Sincerely,

Stan Rosenbaum

**Comment by mjheilmann** [comment]
Stan Rosenbaum

That 500 internal server error is an error generated on the php side with apache.  The install page just doesn't know how to gracefully handle that error.  please check your apache and php logs for any errors.  MGM is also a code-igniter php applicaiton, so it also has its own internal log if the normal apache error logs come up dry.

Michael

**Comment by sdzrosenbaum** [comment]
Ok the Initial PHP error, seems to be due to needing to uncommon the include_path in the PHP.ini.

However, the install page is still not displaying.

The Java Script error is pretty much the same except for the bottom line.   I don't know if the JavaScript function getPreventDefault() being deprecated would be enough to cause the problem, but that is all the new information I have.

Any ideas?

Sincerely,

Stan

====

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. install.html
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] <unknown>
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. install.html

**Comment by mjheilmann** [comment]
That is not enough information for me to take a guess at it.  Since you are already using your browsers development console, have a look at the networking calls javascript is making against the server, and see if there are responses that resemble an html index page, or other error messages.  There is likely a configuration issue somewhere, but it isn't severe enough for the console to recognize it and print it for you.

Michael

**Comment by sdzrosenbaum** [comment]
Actually  I just got the Install page to display.  [Haven't gone much further yet, just enjoying the fact I see the page.]

This is what I did if you want to record it for future reference.
Running on Ubuntu 14.04 - 64bit on  VM.

First Ubuntu's default install of PHP  needs to have the include_path in the php.ini uncommented.
So it looks like so.  [This got me past the initial problem.]

; UNIX: "/path1:/path2"
include_path = ".:/usr/share/php" 

The second part of the problem was I didn't have the hostname specified in the database.ini in 
/mgm/server/application/config

I assumed the base install would default to localhost [since I am running locally].  But I had to specify it in these lines:
$db['default']['hostname'] = 'localhost';
and
$db['opensim']['hostname'] = 'localhost';

Hope this helps someone in the future, and thanks for your help too.  

Peace

Stan

**Comment by sdzrosenbaum** [comment]
One more question... I was able to create the Admin account for MGM, but when I go to the front page to login, I am getting an invalid credentials error.  Any ideas?

Thanks

Stan

**Comment by mjheilmann** [comment]
I am taking a guess here, but moses accounts are de-facto opensim accounts, and are authenticated against the simian front end.  So any moses account is also an avatar account for the grid that you are creating.  This also means that it must follow the rules for an opensim avatar, such as having a first and last name, and the password can't be longer than 16 characters (when using firestorm, if I remember correctly.)

So if you used admin for your account name instead of 'admin user' or similar, you can have problems.  I do not believe the installer page checks this.  The password problem does not affect MGM though, so that only manifests when you attempt to login to a region using a viewer.

I hope one of these helps

Michael
