### ISSUE TITLE
Unable to run install.html

### ISSUE THREAD

**Issue by enochisg** [M-O-S-E-S/mgm#2]
I've completed every step up to install.html. When I do that step, I get a blank white webpage.

I've narrowed down the issue to when install.html calls js/jquery-1.11.0.min.js by commenting out the other JS files

Of note, I entered the information for database.php, but don't know what to add for database driver

Thank you!

**Comment by mjheilmann** [comment]
There are two sets of database credentials in the database.php file.  You should only have to edit hostname, username, password, and database for each of them.

The installation page has a series of content frames that are visible depending on the current state of the web application.  This is normally caused by a php error server-side.  The application queries the MGM backend for installation status, which a php error will respond with code 503.

install.html is a small knockout.js application.  By commenting out javascript pieces you likely saw some content appear, but that also broke the installer.  Please check your php logs server side, or perhaps your web browsers development console.  Note that the php logs could be in your web servers' error log, or also in the MGM logs at server/application/logs.  Simiangrid also has its own internal logging mechanism under each subsection, ie Grid, GridLogin, etc.

I hope that helps.

**Comment by enochisg** [comment]
Thank you for the insight with the MGM logs! It turns out I inadvertently was editing the wrong database.php file and MGM couldn't connect to MySQL.
