### ISSUE TITLE
VivoxVoice

### ISSUE THREAD

**Issue by enochisg** [M-O-S-E-S/mgm#6]
We added VivoxVoice using the ini Editor and restarted the regions yet we still have no voice. Are there additional components that need to be added or is this feature incompatible with a simian or MGM grid?

**Comment by mjheilmann** [comment]
Vivox voice is a third party component to Opensim, and should have little to do with what front-end you are running.  Please reference your regions console (The manage button in MGM when the region is running), or your regions log (the log button to the right of the manage button) for process output to check for errors.  We self-host freeswitch instead of using external services, so MGM is pre-configured for that.

It may be as simple as making sure your Freeswitch is disabled in the ini editor to make sure that you dont have dueling configurations.

If you desire, the configurations that mgmNode writes to your local OpenSim.ini before launch is generated in the function serveOpensimConfig in the file mgm/server/application/libraries/Regions.php.  It does hard-code some values, but freeswitch is not hard-coded on.
